/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Output;

import models.Monster;
import javax.swing.JOptionPane;
/**
 *
 * @author johan
 */
public class frmInputMonster extends javax.swing.JFrame {
    Monster monster = new Monster();
    /**
     * Creates new form frmInputMonster
     */
    public frmInputMonster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNPM = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        labelKodeMK = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        labelTanggal = new javax.swing.JLabel();
        atk = new javax.swing.JTextField();
        labelNilai = new javax.swing.JLabel();
        def = new javax.swing.JTextField();
        labelJumlah = new javax.swing.JLabel();
        spd = new javax.swing.JTextField();
        labelNPM1 = new javax.swing.JLabel();
        hp = new javax.swing.JTextField();
        Simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNPM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNPM.setText("Id :");

        labelKodeMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeMK.setText("Nama :");

        labelTanggal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTanggal.setText("ATK :");

        labelNilai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNilai.setText("DEF :");

        labelJumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelJumlah.setText("SPD :");

        labelNPM1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNPM1.setText("HP :");

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelJumlah)
                    .addComponent(labelNPM1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelTanggal)
                        .addComponent(labelNilai))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNPM)
                            .addComponent(labelKodeMK))
                        .addGap(1, 1, 1)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atk, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Simpan)
                        .addGap(18, 18, 18)
                        .addComponent(batal)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNPM)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeMK)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTanggal)
                    .addComponent(atk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNilai)
                    .addComponent(def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJumlah)
                    .addComponent(spd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNPM1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpan)
                    .addComponent(batal))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        if(monster.validasiId(Integer.parseInt(id.getText()))==0){
            monster.setAtk(Integer.parseInt(atk.getText()));
            monster.setDef(Integer.parseInt(def.getText()));
            monster.setSpd(Integer.parseInt(spd.getText()));
            monster.sethp(Integer.parseInt(hp.getText()));
            monster.setnama(nama.getText());
            monster.setId(Integer.parseInt(id.getText()));
            if(monster.insert()){
                JOptionPane.showMessageDialog(this, "Berhasil Disimpan");
            }
            
        }else {
            monster.setId(Integer.parseInt(id.getText()));
            monster.setAtk(Integer.parseInt(atk.getText()));
            monster.setDef(Integer.parseInt(def.getText()));
            monster.setSpd(Integer.parseInt(spd.getText()));
            monster.sethp(Integer.parseInt(hp.getText()));
            monster.setnama(nama.getText());
            monster.update(Integer.parseInt(id.getText()));
            JOptionPane.showMessageDialog(this, "Data Sudah Terupdate");
        }
        
        
    }//GEN-LAST:event_SimpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        id.setText("");
        nama.setText("");
        atk.setText("");
        def.setText("");
        spd.setText("");
        hp.setText("");
    }//GEN-LAST:event_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInputMonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInputMonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInputMonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInputMonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInputMonster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Simpan;
    private javax.swing.JTextField atk;
    private javax.swing.JButton batal;
    private javax.swing.JTextField def;
    private javax.swing.JTextField hp;
    private javax.swing.JTextField id;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKodeMK;
    private javax.swing.JLabel labelNPM;
    private javax.swing.JLabel labelNPM1;
    private javax.swing.JLabel labelNilai;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField spd;
    // End of variables declaration//GEN-END:variables
}
